
import Navbar from "./components/Navbar";
import "./globals.css";




export const metadata = {
  title: "HelpBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-zinc-900" lang="en">
      <body >
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
