
import Navbar from "./components/Navbar";
import "./globals.css";
import UpperNav from "./components/UpperNav";




export const metadata = {
  title: "HelpBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-zinc-900" lang="en">
      <body >
        <UpperNav/>
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
