export const mockRentals = [
    {
      id: "rental1",
      title: "Mountain Bike",
      description: "Good condition mountain bike available for weekend rentals.",
      points: 30,
      priceType: "per day",
      location: "Building C",
      createdAt: "3 hours ago",
      user: {
        id: "user1",
        name: "Chris Parker",
        image: "/placeholder.svg?height=40&width=40",
      },
      status: "available",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: "rental2",
      title: "Textbook: Introduction to Psychology",
      description: "Latest edition of the psychology textbook for PSY101.",
      points: 20,
      priceType: "per week",
      location: "Library",
      createdAt: "1 day ago",
      user: {
        id: "user2",
        name: "Morgan Lee",
        image: "/placeholder.svg?height=40&width=40",
      },
      status: "available",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: "rental3",
      title: "Portable Projector",
      description: "HD projector perfect for movie nights or presentations.",
      points: 50,
      priceType: "per day",
      location: "Student Center",
      createdAt: "2 days ago",
      user: {
        id: "user3",
        name: "Jordan Smith",
        image: "/placeholder.svg?height=40&width=40",
      },
      status: "available",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: "rental4",
      title: "Tennis Racket Set",
      description: "Two professional tennis rackets with a pack of balls.",
      points: 15,
      priceType: "per day",
      location: "Sports Center",
      createdAt: "3 days ago",
      user: {
        id: "user4",
        name: "Casey Jones",
        image: "/placeholder.svg?height=40&width=40",
      },
      status: "available",
      image: "/placeholder.svg?height=200&width=300",
    },
  ]